### ISSUE TITLE
CI: failed to run katib-controller integration tests

### ISSUE THREAD

**Issue by NohaIhab** [canonical/katib-operators#119]
logs:
```
Run sg microk8s -c "tox -e controller-integration"
  sg microk8s -c "tox -e controller-integration"
  shell: /usr/bin/bash -e {0}
  env:
    CONTROLLER_NAME: github-pr-e977c-microk8s
ROOT: HandledError| provided environments not found in configuration file: ['controller-integration']
```
came up in [this run](https://github.com/canonical/katib-operators/actions/runs/5882367399)

**Comment by phoevos** [comment]
So it looks like this run uses the latest [tox 4.9.0](https://tox.wiki/en/latest/changelog.html#features-4-9-0) released yesterday. The release introduces the following change:
> Disallow command line environments which are not explicitly specified in the config file

This breaks our CI, which attempts to use the `controller-integration` testenv:
https://github.com/canonical/katib-operators/blob/a9c7609d28dcbf204d37fa586bf3bf67133d9a30/.github/workflows/integrate.yaml#L82

`controller-integration` is not included in the `envlist`, however, but rather `katib-controller-integration` is:
https://github.com/canonical/katib-operators/blob/a9c7609d28dcbf204d37fa586bf3bf67133d9a30/tox.ini#L10

Previously, this would not matter, since explicitly specifying the environment would bypass the `envlist` and the proper command would be set here (pattern matching works properly because both "controller" and "integration" are in the provided environment name): https://github.com/canonical/katib-operators/blob/a9c7609d28dcbf204d37fa586bf3bf67133d9a30/tox.ini#L19-L26

### Solution

Following the latest tox release we will have to provide the correct environment name (i.e. `katib-controller-integration`) in the charm matrix: https://github.com/canonical/katib-operators/blob/a9c7609d28dcbf204d37fa586bf3bf67133d9a30/.github/workflows/integrate.yaml#L63-L65

**Comment by phoevos** [comment]
Note, we will have to check whether other parts of this or other repositories are potentially affected by this change.
